/**
 * Constants
 * */
const constants = {
    //User Roles
    CONST_ROLE_DEVELOPER : 1,
    CONST_ROLE_SUPER_ADMIN : 2,
    CONST_ROLE_COMPANY_ADMIN : 3,
    CONST_ROLE_USER : 4,

    //Dropdowns
    CONST_INSTITUTE: 1,
    CONST_SKILL_NAME: 3,
    CONST_SKILL_SCALE: 4,
    CONST_DESIGNATION: 5,
    CONST_EMPLOYEE_TYPE: 6,
    CONST_RELIGION: 7,
    CONST_DEGREE_NAME: 8,
    CONST_DIVISION: 9,
    CONST_RELATIONSHIP_TYPE: 10,
    CONST_CITY: 11,
    CONST_BLOOD_GROUP: 12,
    CONST_NATIONALITY: 13,
    CONST_GENDER: 14,
    CONST_ORG_TYPE: 19,
    CONST_RC_CODE: 20,
    CONST_ID_REQ_REASON: 24,
    CONST_DD_DOCUMENT_TYPES: 26,
    CONST_MARITAL: 17,
    CONST_STATIONARY_ITEM: 25,
    CONST_OVERTIME_TYPES: 16,
    CONST_TRANSPORT_TYPES: 27,
    CONST_LOCATION_ITEMS: 28,
    CONST_HR_ITEMS: 29,
    CONST_COC_ITEMS: 30,
    CONST_OT_TYPES: 31,







    //Education Level
    CONST_PSC: 20,
    CONST_JSC: 21,
    CONST_SSC: 22,
    CONST_HSC: 23,
    CONST_GRADUATION: 24,
    CONST_POST_GRAD: 25,


    //Master Package
    CONST_LEAVE_PACKAGE: 1,
    CONST_JOB_DESCRIPTION: 2,
    CONST_ASSET_PACKAGE: 3,
    CONST_PAYROLL_PACKAGE: 4,
}
export default constants
